local contracts = require("neph.internal.contracts")

describe("backend contract conformance", function()
  it("snacks backend passes validation", function()
    local snacks = require("neph.backends.snacks")
    assert.has_no.errors(function()
      contracts.validate_backend(snacks, "snacks")
    end)
  end)

  it("wezterm backend passes validation", function()
    local wezterm = require("neph.backends.wezterm")
    assert.has_no.errors(function()
      contracts.validate_backend(wezterm, "wezterm")
    end)
  end)

  it("zellij backend passes validation", function()
    local zellij = require("neph.backends.zellij")
    assert.has_no.errors(function()
      contracts.validate_backend(zellij, "zellij")
    end)
    assert.is_true(zellij.single_pane_only)
    assert.is_function(zellij.send)
  end)
end)
