---@diagnostic disable: undefined-global
-- file_refresh_spec.lua -- tests for neph.internal.file_refresh

local file_refresh

describe("neph.internal.file_refresh", function()
  before_each(function()
    package.loaded["neph.internal.file_refresh"] = nil
    file_refresh = require("neph.internal.file_refresh")
  end)

  after_each(function()
    file_refresh.teardown()
  end)

  describe("setup with enable = false", function()
    it("does not create a timer", function()
      file_refresh.setup({ file_refresh = { enable = false } })
      -- teardown should be safe (no timer to stop)
      assert.has_no_errors(function()
        file_refresh.teardown()
      end)
    end)
  end)

  describe("setup with enable = true", function()
    it("creates timer and autocmds without error", function()
      assert.has_no_errors(function()
        file_refresh.setup({ file_refresh = { enable = true, interval = 500 } })
      end)
    end)
  end)

  describe("setup with nil config", function()
    it("does not error when config is nil", function()
      assert.has_no_errors(function()
        file_refresh.setup(nil)
      end)
    end)
  end)

  describe("setup with empty config", function()
    it("does not error when file_refresh key is missing", function()
      assert.has_no_errors(function()
        file_refresh.setup({})
      end)
    end)
  end)

  describe("teardown idempotency", function()
    it("can be called multiple times safely", function()
      file_refresh.setup({ file_refresh = { enable = true, interval = 1000 } })
      assert.has_no_errors(function()
        file_refresh.teardown()
        file_refresh.teardown()
        file_refresh.teardown()
      end)
    end)

    it("can be called without prior setup", function()
      assert.has_no_errors(function()
        file_refresh.teardown()
      end)
    end)
  end)

  describe("setup is idempotent", function()
    it("calling setup twice does not leak timers", function()
      assert.has_no_errors(function()
        file_refresh.setup({ file_refresh = { enable = true, interval = 1000 } })
        file_refresh.setup({ file_refresh = { enable = true, interval = 2000 } })
      end)
      -- cleanup
      file_refresh.teardown()
    end)
  end)

  describe("setup with interval = 0", function()
    it("does not error with zero interval", function()
      assert.has_no_errors(function()
        file_refresh.setup({ file_refresh = { enable = true, interval = 0 } })
      end)
      file_refresh.teardown()
    end)
  end)

  describe("setup then teardown then setup", function()
    it("can reinitialize after teardown", function()
      assert.has_no_errors(function()
        file_refresh.setup({ file_refresh = { enable = true, interval = 1000 } })
        file_refresh.teardown()
        file_refresh.setup({ file_refresh = { enable = true, interval = 500 } })
        file_refresh.teardown()
      end)
    end)
  end)
end)
